### ISSUE TITLE
Error al recargar la vista de un local

### ISSUE THREAD

**Issue by pabloacevedo** [growlerapp/webapp#17]
Se cuelga la app al recargar o al acceder al link directo de un local.

Por ejemplo: https://www.growlerapp.cl/#/store/5ada2ac13d1cc800120bf7a3

![image](https://user-images.githubusercontent.com/729132/54311913-5c828c00-45b4-11e9-8986-e7acd573cdec.png)

**Comment by lgaticaq** [comment]
@pabloacevedo solucionado en [v0.2.0](https://github.com/growlerapp/webapp/releases/tag/v0.2.0)
