### ISSUE TITLE
No carga en ubuntu

### ISSUE THREAD

**Issue by rcarmonad** [growlerapp/webapp#5]
No me carga nah la app ni en firefox nor chromium.
No se que será o que les puedo agregar acá pa que revisen.
Eso.
xoxo

**Comment by lgaticaq** [comment]
@rcarmonad de casualidad te pidió usar la geolocalización?

**Comment by raulghm** [comment]
@rcarmonad si puedes agregar mas info, version de ubuntu, firefox o chromium

**Comment by rcarmonad** [comment]
En ambos casos me pidio usar geolocalizacion, y dije que _**demas que yes**_

```
Ubuntu 18.04
Firefox Quantum 60.0.1 (64-bit)
Chromium Version 66.0.3359.181 (Official Build) (64-bit)
```

**Comment by lgaticaq** [comment]
@rcarmonad te sigue el error porque se lanzaron varias cambios

**Comment by rcarmonad** [comment]
Ubuntu 18.10 con Chrome carga, lento pero carga.
Mismo SO, con Firefox carga un poco mas rápido.

* c cierra *
